# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: New Standard Power Technical Co. Ltd

description: > # this means to ignore newlines until "baseurl:"
  Auxiliary Power Support, Intelligent Online and Offline Monitoring System, Transformer Circuit Breaker for Large-scaled Power Plants.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://newstandardpower.com" # the base hostname & protocol for your site
include: ['_pages']

# Build settings
markdown: kramdown
